# Generated by Django 2.1.1 on 2018-10-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181011_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
