# Generated by Django 2.1.1 on 2018-10-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20181012_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user_id',
            new_name='user',
        ),
    ]
